### ISSUE TITLE
[Tasks] Blocksnmore

### ISSUE THREAD

**Issue by quick007** [CoursifyStudios/Coursify#210]
# Coursify Task list

Mention this issue in any commits and/or pull requests you make to track progress. <br>
Once something is finished check it off. <br>
Feel free to use the comments for noting items.

## User

@Blocksnmore 

## Tasks

- [ ] Assignments
    - [x] Pagination
    - [ ] Searching
    - [ ] Sorting
    - [ ] Filters
    - [ ] Assignments fix for admins
- [ ] Admin
    - [x] Add existing users
    - [ ] Remove users - Coded but not tested
- [x] #211
    - [x] Remake sql login function
- [x] #195 
- [x] #213 

## Target finish date

soon:tm:
