### ISSUE TITLE
[Tasks] brandon

### ISSUE THREAD

**Issue by quick007** [CoursifyStudios/Coursify#212]
# Coursify Task list

Mention this issue in any commits and/or pull requests you make to track progress. <br>
Once something is finished check it off. <br>
Feel free to use the comments for noting items.

## User

@brandnholl 

## Tasks

- [x] Add default gradient for non-onboarded users #215 
- [x] Review #206 
- [x] Fix agendas #193 
- [x] #213
- [x] add a placeholder for when user has no starred assignments #217 
- [x] find cause of profile error (and maybe classes not loading too, see my profile for an example)
- [x] create emails for start of school #228 
- [x] hovering in wrong place on copied hover breaks stuff
- [ ] Hunt for other bugs that need to be fixed
- [ ] Email stuff

## Target finish date

N/A
