### ISSUE TITLE
[Tasks] bill

### ISSUE THREAD

**Issue by quick007** [CoursifyStudios/Coursify#222]
# Coursify Task list

Mention this issue in any commits and/or pull requests you make to track progress. <br>
Once something is finished check it off. <br>
Feel free to use the comments for noting items.

## User

@IllGive 

## Tasks

- [x] #193 
    - [x] Need to display their specific assignments
- [ ] Look for general bugs around the website (not a pdf or any text/rich text document (i.e. docx), use github issues)
- [ ] #100  NO
- [ ] School announcements
- [ ] File Upload
  - [ ] Agendas #248 
  - [ ] Announcements #249 
  - [ ] Assignments #250
- [ ] All schedule templates
  - [x] Gold
  - [x] Green
  - [x] Blue
  - [ ] All Founders types
    - [ ]
  - [ ] Mass Day
- [x] At least a week of schedules
- [x] Announcement Comments #227 
    - [x] Editing
    - [x] Deleting
- [ ] Replying

## Target finish date

N/A
